name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v4
        with:
          ref: main
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      
      - name: Install Hexo CLI
        run: |
          export TZ='Asia/Taipei'
          npm install hexo-cli -g
      
      - name: Cache Dependencies
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}
      
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install

      - name: Hexo Static Files Generation
        run: |
          hexo clean
          hexo generate

      - name: Deploy
        run: |
          git config --global user.name "$GITHUB_USERNAME"
          git config --global user.email "$GITHUB_EMAIL"
          
          cd ./public
          git init
          git add .
          git commit -m "Deploy: $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By GitHub Actions"

          # 使用 GitHub Token 來推送
          git remote add origin "https://github.com/$GITHUB_USERNAME/hy-blog.git"
          git branch -M gh-pages-prod
          git push --force origin gh-pages-prod
