name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - name: Install Hexo CLI
        run: |
          export TZ='Asia/Taipei'
          npm install hexo-cli -g
      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Hexo Static Files Generation
        run: |
          hexo clean
          hexo generate
      - name: Deploy
        run: |
          # 先設定 Git 使用者資訊
          git config --global user.name "${{ secrets.GITHUBUSERNAME }}"
          git config --global user.email "${{ secrets.GITHUBEMAIL }}"
          # 設定預設分支名稱為 main
          git config --global init.defaultBranch main
          
          cd ./public
          # 初始化 Git 倉庫
          [ -d .git ] || git init
          # 加入檔案，提交更改
          git add .
          git commit -m "${{ github.event.head_commit.message }} $(date +"%Z %Y-%m-%d %A %H:%M:%S") Updated By Github Actions"
          # 推送到 gh-pages-prod 分支
          git push --force --quiet "https://${{ secrets.GITHUBUSERNAME }}:${{ secrets.GITHUBTOKEN }}@github.com/${{ secrets.GITHUBUSERNAME }}/${{ secrets.GITHUBUSERNAME }}.github.io.git" main:gh-pages-prod